### ISSUE TITLE
First buff in Buff.Spells is never applied

### ISSUE THREAD

**Issue by MrLavender** [azerothcore/mod-npc-buffer#26]
### Current Behaviour

First buff in Buff.Spells list is never applied.

### Expected Blizzlike Behaviour

First buff in Buff.Spells list should be applied.

### Source

C++ vector indexes start at 0 not 1. Code like this should be 0 to 5 not 1 to 6.
```
    player->CastSpell(player, vecBuffs[1], true); // Prayer of Fortitude(48162)
    player->CastSpell(player, vecBuffs[2], true); // Greater Blessing of Kings(43223)
    player->CastSpell(player, vecBuffs[3], true); // Mark of the Wild(48469)
    player->CastSpell(player, vecBuffs[4], true); // Prayer of Spirit(48074)
    player->CastSpell(player, vecBuffs[5], true); // Prayer of Shadow Protection(48170)
    player->CastSpell(player, vecBuffs[6], true); // Arcane Intellect(36880)
```

### Steps to reproduce the problem

1. Right-click buffer npc
2. Don't receive Prayer of Fortitude(48162) buff

### AC rev. hash/commit

AzerothCore rev. f71ce38d7d00 2022-09-21 19:47:48 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Linux 5.19.7-1-MANJARO x86_64

**Comment by pangolp** [comment]
I just tested, and this is correct. The vector is actually full range, and in the console, an error message appears. So we have to correct this. I'll upload a pull request to add it, thanks.
