### ISSUE TITLE
Arcane Intellect buff uses NPC abilities instead of player spells

### ISSUE THREAD

**Issue by MrLavender** [azerothcore/mod-npc-buffer#27]
### Current Behaviour

https://www.wowhead.com/wotlk/spell=36880/arcane-intellect is an ability used by a NPC in the The Arcatraz which increases intellect by 100.

https://www.wowhead.com/wotlk/spell=42995/arcane-intellect is the L80 (Rank 7) player spell which increases intellect by 60.

And for lower levels https://www.wowhead.com/wotlk/spell=13326/arcane-intellect is used instead of the lower rank player spells.

### Expected Blizzlike Behaviour

Arcane Intellect buff should give +60 intellect not +100.

### Steps to reproduce the problem

1. Right-click on buffer npc
2. Receive Arcane Intellect +100 intellect buff

### AC rev. hash/commit

AzerothCore rev. f71ce38d7d00 2022-09-21 19:47:48 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Linux 5.19.7-1-MANJARO x86_64

**Comment by pangolp** [comment]
I just ran tests, and you are right. I'm going to make a pull request to fix it. Thank you.

![WoWScrnShot_032724_030829](https://github.com/azerothcore/mod-npc-buffer/assets/2810187/b4e2660a-89ad-4d4b-b611-0ae7510d5b3d)
