### ISSUE TITLE
Misspell

### ISSUE THREAD

**Issue by bblrlo** [azerothcore/mod-npc-buffer#33]
https://github.com/azerothcore/mod-npc-buffer/blob/63bf540d6525cfc8b1dfcc856885bed3d00d7545/src/npc_buffer.cpp#L141

getLevel -> GetLevel

28.95 /azerothcore/modules/mod-npc-buffer/src/npc_buffer.cpp:141:32: fatal error: no member named 'getLevel' in 'Player'; did you mean 'GetLevel'?
28.95         uint32 level = player->getLevel();

**Comment by Helias** [comment]
I made a PR about this https://github.com/azerothcore/mod-npc-buffer/pull/34
thanks for the report
