### ISSUE TITLE
Compile failure: sSpellMgr is undeclared

### ISSUE THREAD

**Issue by GroodeeshPanj** [azerothcore/mod-npc-buffer#38]
### Current Behaviour

`/azerothcore/modules/mod-npc-buffer/src/npc_buffer.cpp:146:20: fatal error: use of undeclared identifier 'sSpellMgr'
  146 |             return sSpellMgr->GetLastSpellInChain(spell_id);
      |                    ^
`

### Expected Blizzlike Behaviour

N/A (code should compile)

### Steps to reproduce the problem

Check out after 

[https://github.com/azerothcore/azerothcore-wotlk/commit/cb7e28df0579c73d0aaa29ee7406a653aee548d8](url) which I believe to be the issue where it removes spellmgr.h among other things. However I'm not a coder, but I do know the module would compile with 

`AzerothCore rev. 6194cc864bd7 2024-10-26 21:58:53 +0000` 

this version.

### AC rev. hash/commit

Current working commit: AzerothCore rev. 6194cc864bd7 2024-10-26 21:58:53 +0000

Trying to build commit a60100d65dac2110ae49ff576d9c3ca0178cc27f today and it doesn't work.

### Operating system

Ubuntu 24.04

### Custom changes or Modules

List of enabled modules:
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants

**Comment by MIXXtlt** [comment]
The problem on OS win is not resolved.
