### ISSUE TITLE
Priest buff Fortitude

### ISSUE THREAD

**Issue by poszer** [azerothcore/mod-npc-buffer#8]
https://github.com/azerothcore/mod-npc-buffer/blob/2d0bac68403d5a5721e9eed8cc11cc6dbf7d1e4b/src/npc_buffer.cpp#L288
Doesn't work. Should be created with .aura maybe ?

**Comment by milestorme** [comment]
Replace `vecBuffs [1] ` 48162 works fine just casting the spell id

**Comment by poszer** [comment]
> Replace `vecBuffs [1] ` with `48162` works fine just casting the spell id

kk thanks
