### ISSUE TITLE
Complie error with docker build

### ISSUE THREAD

**Issue by th3lolipop** [azerothcore/mod-npc-buffer#9]
Is there some compile error with docker build ?

**Comment by FrancescoBorzi** [comment]
@th3lolipop are you getting any error? if yes, paste it

**Comment by th3lolipop** [comment]
**ERROR START**

> Scanning dependencies of target scripts
[ 38%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/GenLoader.cpp.o
[ 38%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-buffer/src/npc_buffer.cpp.o
/azerothcore/modules/mod-npc-buffer/src/npc_buffer.cpp:186:89: fatal error: unused parameter 'uiAction' [-Wunused-parameter]
    bool OnGossipSelect(Player *player, Creature *creature, uint32 /*uiSender*/, uint32 uiAction)
                                                                                        ^
1 error generated.
src/server/scripts/CMakeFiles/scripts.dir/build.make:13977: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-buffer/src/npc_buffer.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-buffer/src/npc_buffer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1329: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**ERROR ENDED**

Firstly, Thanks for your prompt reply @FrancescoBorzi  

**The Problem**

I can complie with Normal ( Classic Installation ) but i can't compile with Docker Installation and got this issue

**Comment by FrancescoBorzi** [comment]
@th3lolipop thanks for your feedback, are you sure this issue is caused by the module? have you tried without it?

**Comment by th3lolipop** [comment]
@FrancescoBorzi  Sure, it caused by the module . Without this module, things are going well  :)

**Comment by FrancescoBorzi** [comment]
so it happens only with the module and only on docker... quite weird, thanks for reporting it

**Comment by Helias** [comment]
This build problem has beend fixed here https://github.com/azerothcore/mod-npc-buffer/pull/10
